# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'category.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_category(object):
    def setupUi(self, category):
        category.setObjectName("category")
        category.resize(400, 300)
        self.gridLayout_2 = QtWidgets.QGridLayout(category)
        self.gridLayout_2.setObjectName("gridLayout_2")

        self.retranslateUi(category)
        QtCore.QMetaObject.connectSlotsByName(category)

    def retranslateUi(self, category):
        _translate = QtCore.QCoreApplication.translate
        category.setWindowTitle(_translate("category", "Form"))
