# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'favorite.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_favorite(object):
    def setupUi(self, favorite):
        favorite.setObjectName("favorite")
        favorite.resize(451, 292)
        self.gridLayout_2 = QtWidgets.QGridLayout(favorite)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.nums = QtWidgets.QLabel(favorite)
        self.nums.setObjectName("nums")
        self.horizontalLayout.addWidget(self.nums)
        self.pages = QtWidgets.QLabel(favorite)
        self.pages.setObjectName("pages")
        self.horizontalLayout.addWidget(self.pages)
        self.comboBox = QtWidgets.QComboBox(favorite)
        self.comboBox.setMinimumSize(QtCore.QSize(75, 0))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.lineEdit = QtWidgets.QLineEdit(favorite)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.jumpButton = QtWidgets.QPushButton(favorite)
        self.jumpButton.setObjectName("jumpButton")
        self.horizontalLayout.addWidget(self.jumpButton)
        self.gridLayout_4.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2.addLayout(self.gridLayout_3, 0, 0, 1, 1)

        self.retranslateUi(favorite)
        self.jumpButton.clicked.connect(favorite.JumpPage)
        self.comboBox.currentIndexChanged['int'].connect(favorite.RefreshDataFocus)
        QtCore.QMetaObject.connectSlotsByName(favorite)

    def retranslateUi(self, favorite):
        _translate = QtCore.QCoreApplication.translate
        favorite.setWindowTitle(_translate("favorite", "Form"))
        self.nums.setText(_translate("favorite", "收藏数："))
        self.pages.setText(_translate("favorite", "页"))
        self.comboBox.setItemText(0, _translate("favorite", "从旧到新"))
        self.comboBox.setItemText(1, _translate("favorite", "从新到旧"))
        self.jumpButton.setText(_translate("favorite", "跳转"))
