# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'history.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_History(object):
    def setupUi(self, History):
        History.setObjectName("History")
        History.resize(400, 292)
        self.gridLayout_2 = QtWidgets.QGridLayout(History)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.nums = QtWidgets.QLabel(History)
        self.nums.setObjectName("nums")
        self.horizontalLayout.addWidget(self.nums)
        self.pages = QtWidgets.QLabel(History)
        self.pages.setObjectName("pages")
        self.horizontalLayout.addWidget(self.pages)
        self.lineEdit = QtWidgets.QLineEdit(History)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.jumpButton = QtWidgets.QPushButton(History)
        self.jumpButton.setObjectName("jumpButton")
        self.horizontalLayout.addWidget(self.jumpButton)
        self.gridLayout_4.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2.addLayout(self.gridLayout_3, 0, 0, 1, 1)

        self.retranslateUi(History)
        self.jumpButton.clicked.connect(History.JumpPage)
        QtCore.QMetaObject.connectSlotsByName(History)

    def retranslateUi(self, History):
        _translate = QtCore.QCoreApplication.translate
        History.setWindowTitle(_translate("History", "Form"))
        self.nums.setText(_translate("History", "收藏数："))
        self.pages.setText(_translate("History", "页"))
        self.jumpButton.setText(_translate("History", "跳转"))
