# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtepsinfo.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EpsInfo(object):
    def setupUi(self, EpsInfo):
        EpsInfo.setObjectName("EpsInfo")
        EpsInfo.resize(526, 82)
        self.gridLayout_2 = QtWidgets.QGridLayout(EpsInfo)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(EpsInfo)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.pushButton = QtWidgets.QPushButton(EpsInfo)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(EpsInfo)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(EpsInfo)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(EpsInfo)
        self.pushButton.clicked.connect(EpsInfo.SelectAll)
        self.pushButton_2.clicked.connect(EpsInfo.CancleSelect)
        self.pushButton_3.clicked.connect(EpsInfo.StartDownload)
        QtCore.QMetaObject.connectSlotsByName(EpsInfo)

    def retranslateUi(self, EpsInfo):
        _translate = QtCore.QCoreApplication.translate
        EpsInfo.setWindowTitle(_translate("EpsInfo", "Form"))
        self.label.setText(_translate("EpsInfo", "章节"))
        self.pushButton.setText(_translate("EpsInfo", "全选"))
        self.pushButton_2.setText(_translate("EpsInfo", "反选"))
        self.pushButton_3.setText(_translate("EpsInfo", "下载"))
