# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'readimg.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReadImg(object):
    def setupUi(self, ReadImg):
        ReadImg.setObjectName("ReadImg")
        ReadImg.resize(402, 509)
        self.gridLayout_2 = QtWidgets.QGridLayout(ReadImg)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphicsView = QtWidgets.QGraphicsView(ReadImg)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)
        self.epsLabel = QtWidgets.QLabel(ReadImg)
        self.epsLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.epsLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.epsLabel.setObjectName("epsLabel")
        self.verticalLayout.addWidget(self.epsLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lastPage = QtWidgets.QPushButton(ReadImg)
        self.lastPage.setMinimumSize(QtCore.QSize(0, 40))
        self.lastPage.setMaximumSize(QtCore.QSize(16777215, 40))
        self.lastPage.setObjectName("lastPage")
        self.horizontalLayout.addWidget(self.lastPage)
        self.returePage = QtWidgets.QPushButton(ReadImg)
        self.returePage.setMinimumSize(QtCore.QSize(0, 40))
        self.returePage.setMaximumSize(QtCore.QSize(16777215, 40))
        self.returePage.setObjectName("returePage")
        self.horizontalLayout.addWidget(self.returePage)
        self.nextPage = QtWidgets.QPushButton(ReadImg)
        self.nextPage.setMinimumSize(QtCore.QSize(0, 40))
        self.nextPage.setMaximumSize(QtCore.QSize(16777215, 40))
        self.nextPage.setObjectName("nextPage")
        self.horizontalLayout.addWidget(self.nextPage)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(ReadImg)
        self.lastPage.clicked.connect(ReadImg.LastPage)
        self.nextPage.clicked.connect(ReadImg.NextPage)
        self.returePage.clicked.connect(ReadImg.ReturnPage)
        QtCore.QMetaObject.connectSlotsByName(ReadImg)

    def retranslateUi(self, ReadImg):
        _translate = QtCore.QCoreApplication.translate
        ReadImg.setWindowTitle(_translate("ReadImg", "Form"))
        self.epsLabel.setText(_translate("ReadImg", "TextLabel"))
        self.lastPage.setText(_translate("ReadImg", "上一页"))
        self.returePage.setText(_translate("ReadImg", "返回"))
        self.nextPage.setText(_translate("ReadImg", "下一页"))
