# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'readimg.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReadImg(object):
    def setupUi(self, ReadImg):
        ReadImg.setObjectName("ReadImg")
        ReadImg.resize(158, 253)
        self.gridLayout_2 = QtWidgets.QGridLayout(ReadImg)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.epsLabel = QtWidgets.QLabel(ReadImg)
        self.epsLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.epsLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.epsLabel.setObjectName("epsLabel")
        self.verticalLayout.addWidget(self.epsLabel)
        self.lastPage = QtWidgets.QPushButton(ReadImg)
        self.lastPage.setMinimumSize(QtCore.QSize(0, 0))
        self.lastPage.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lastPage.setObjectName("lastPage")
        self.verticalLayout.addWidget(self.lastPage)
        self.nextPage = QtWidgets.QPushButton(ReadImg)
        self.nextPage.setMinimumSize(QtCore.QSize(0, 0))
        self.nextPage.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.nextPage.setObjectName("nextPage")
        self.verticalLayout.addWidget(self.nextPage)
        self.pushButton = QtWidgets.QPushButton(ReadImg)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.radioButton = QtWidgets.QRadioButton(ReadImg)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.buttonGroup = QtWidgets.QButtonGroup(ReadImg)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton)
        self.verticalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(ReadImg)
        self.radioButton_2.setObjectName("radioButton_2")
        self.buttonGroup.addButton(self.radioButton_2)
        self.verticalLayout.addWidget(self.radioButton_2)
        self.returePage = QtWidgets.QPushButton(ReadImg)
        self.returePage.setMinimumSize(QtCore.QSize(0, 0))
        self.returePage.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.returePage.setObjectName("returePage")
        self.verticalLayout.addWidget(self.returePage)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(ReadImg)
        self.lastPage.clicked.connect(ReadImg.LastPage)
        self.nextPage.clicked.connect(ReadImg.NextPage)
        self.returePage.clicked.connect(ReadImg.ReturnPage)
        self.radioButton_2.clicked.connect(ReadImg.SwitchPicture)
        self.radioButton.clicked.connect(ReadImg.SwitchPicture)
        QtCore.QMetaObject.connectSlotsByName(ReadImg)
        ReadImg.setTabOrder(self.returePage, self.nextPage)
        ReadImg.setTabOrder(self.nextPage, self.pushButton)
        ReadImg.setTabOrder(self.pushButton, self.radioButton)
        ReadImg.setTabOrder(self.radioButton, self.radioButton_2)
        ReadImg.setTabOrder(self.radioButton_2, self.lastPage)

    def retranslateUi(self, ReadImg):
        _translate = QtCore.QCoreApplication.translate
        ReadImg.setWindowTitle(_translate("ReadImg", "Form"))
        self.epsLabel.setText(_translate("ReadImg", "TextLabel"))
        self.lastPage.setText(_translate("ReadImg", "上一页"))
        self.nextPage.setText(_translate("ReadImg", "下一页"))
        self.pushButton.setText(_translate("ReadImg", "全屏"))
        self.radioButton.setText(_translate("ReadImg", "正常模式"))
        self.radioButton_2.setText(_translate("ReadImg", "条漫模式"))
        self.returePage.setText(_translate("ReadImg", "返回"))
