# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'search.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_search(object):
    def setupUi(self, search):
        search.setObjectName("search")
        search.resize(613, 585)
        self.gridLayout_2 = QtWidgets.QGridLayout(search)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.searchEdit = QtWidgets.QLineEdit(search)
        self.searchEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.searchEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.searchEdit.setObjectName("searchEdit")
        self.horizontalLayout.addWidget(self.searchEdit)
        self.comboBox = QtWidgets.QComboBox(search)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.searchButton = QtWidgets.QPushButton(search)
        self.searchButton.setMinimumSize(QtCore.QSize(0, 30))
        self.searchButton.setMaximumSize(QtCore.QSize(16777215, 30))
        self.searchButton.setObjectName("searchButton")
        self.horizontalLayout.addWidget(self.searchButton)
        self.label = QtWidgets.QLabel(search)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.jumpLine = QtWidgets.QLineEdit(search)
        self.jumpLine.setObjectName("jumpLine")
        self.horizontalLayout.addWidget(self.jumpLine)
        self.jumpPage = QtWidgets.QPushButton(search)
        self.jumpPage.setMinimumSize(QtCore.QSize(0, 30))
        self.jumpPage.setMaximumSize(QtCore.QSize(16777215, 30))
        self.jumpPage.setObjectName("jumpPage")
        self.horizontalLayout.addWidget(self.jumpPage)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.bookLayout = QtWidgets.QGridLayout()
        self.bookLayout.setObjectName("bookLayout")
        self.gridLayout_2.addLayout(self.bookLayout, 0, 0, 1, 1)
        self.comboBoxLayout = QtWidgets.QVBoxLayout()
        self.comboBoxLayout.setObjectName("comboBoxLayout")
        self.groupBox = QtWidgets.QGroupBox(search)
        self.groupBox.setObjectName("groupBox")
        self.comboBoxLayout.addWidget(self.groupBox)
        self.gridLayout_2.addLayout(self.comboBoxLayout, 2, 0, 1, 1)

        self.retranslateUi(search)
        self.searchButton.clicked.connect(search.Search)
        self.jumpPage.clicked.connect(search.JumpPage)
        self.comboBox.currentIndexChanged['int'].connect(search.ChangeSort)
        QtCore.QMetaObject.connectSlotsByName(search)

    def retranslateUi(self, search):
        _translate = QtCore.QCoreApplication.translate
        search.setWindowTitle(_translate("search", "Form"))
        self.comboBox.setItemText(0, _translate("search", "新到旧"))
        self.comboBox.setItemText(1, _translate("search", "旧到新"))
        self.comboBox.setItemText(2, _translate("search", "最多爱心"))
        self.comboBox.setItemText(3, _translate("search", "最多绅士指数"))
        self.searchButton.setText(_translate("search", "搜索"))
        self.label.setText(_translate("search", "页：0/0"))
        self.jumpPage.setText(_translate("search", "跳转"))
        self.groupBox.setTitle(_translate("search", "GroupBox"))
